2025-05-08 22:28:12,279 INFO    MainThread:45898 [wandb_setup.py:_flush():77] Current SDK version is 0.18.1
2025-05-08 22:28:12,279 INFO    MainThread:45898 [wandb_setup.py:_flush():77] Configure stats pid to 45898
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_setup.py:_flush():77] Loading settings from /public/home/xiangyuduan/.config/wandb/settings
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_setup.py:_flush():77] Loading settings from /public/home/xiangyuduan/lyt/bad_word/train/wandb/settings
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_setup.py:_flush():77] Applying setup settings: {'mode': None, '_disable_service': None}
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': '/public/home/xiangyuduan/lyt/bad_word/train/train.py', 'program': '/public/home/xiangyuduan/lyt/bad_word/train/train.py'}
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_setup.py:_flush():77] Applying login settings: {}
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_init.py:_log_setup():532] Logging user logs to /public/home/xiangyuduan/lyt/bad_word/train/wandb/run-20250508_222812-e2r887kj/logs/debug.log
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_init.py:_log_setup():533] Logging internal logs to /public/home/xiangyuduan/lyt/bad_word/train/wandb/run-20250508_222812-e2r887kj/logs/debug-internal.log
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_init.py:init():616] calling init triggers
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_init.py:init():623] wandb.init called with sweep_config: {}
config: {}
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_init.py:init():666] starting backend
2025-05-08 22:28:12,280 INFO    MainThread:45898 [wandb_init.py:init():670] setting up manager
2025-05-08 22:28:12,282 INFO    MainThread:45898 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-08 22:28:12,291 INFO    MainThread:45898 [wandb_init.py:init():678] backend started and connected
2025-05-08 22:28:12,295 INFO    MainThread:45898 [wandb_init.py:init():773] updated telemetry
2025-05-08 22:28:12,321 INFO    MainThread:45898 [wandb_init.py:init():806] communicating run to backend with 90.0 second timeout
2025-05-08 22:29:00,354 WARNING MainThread:45898 [wandb_init.py:init():1245] interrupted
Traceback (most recent call last):
  File "/public/home/xiangyuduan/anaconda3/envs/rstar/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1241, in init
    return wi.init()
  File "/public/home/xiangyuduan/anaconda3/envs/rstar/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 809, in init
    result = run_init_handle.wait(
  File "/public/home/xiangyuduan/anaconda3/envs/rstar/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/public/home/xiangyuduan/anaconda3/envs/rstar/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/public/home/xiangyuduan/anaconda3/envs/rstar/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/public/home/xiangyuduan/anaconda3/envs/rstar/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/public/home/xiangyuduan/anaconda3/envs/rstar/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2025-05-08 22:29:00,368 WARNING MsgRouterThr:45898 [router.py:message_loop():77] message_loop has been closed
