2025-05-08 22:25:10,905 INFO    MainThread:40425 [wandb_setup.py:_flush():77] Current SDK version is 0.18.1
2025-05-08 22:25:10,905 INFO    MainThread:40425 [wandb_setup.py:_flush():77] Configure stats pid to 40425
2025-05-08 22:25:10,905 INFO    MainThread:40425 [wandb_setup.py:_flush():77] Loading settings from /public/home/xiangyuduan/.config/wandb/settings
2025-05-08 22:25:10,905 INFO    MainThread:40425 [wandb_setup.py:_flush():77] Loading settings from /public/home/xiangyuduan/lyt/bad_word/train/wandb/settings
2025-05-08 22:25:10,905 INFO    MainThread:40425 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2025-05-08 22:25:10,905 INFO    MainThread:40425 [wandb_setup.py:_flush():77] Applying setup settings: {'mode': None, '_disable_service': None}
2025-05-08 22:25:10,905 INFO    MainThread:40425 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': '/public/home/xiangyuduan/lyt/bad_word/train/train.py', 'program': '/public/home/xiangyuduan/lyt/bad_word/train/train.py'}
2025-05-08 22:25:10,906 INFO    MainThread:40425 [wandb_setup.py:_flush():77] Applying login settings: {}
2025-05-08 22:25:10,906 INFO    MainThread:40425 [wandb_init.py:_log_setup():532] Logging user logs to /public/home/xiangyuduan/lyt/bad_word/train/wandb/run-20250508_222510-recjwpp0/logs/debug.log
2025-05-08 22:25:10,906 INFO    MainThread:40425 [wandb_init.py:_log_setup():533] Logging internal logs to /public/home/xiangyuduan/lyt/bad_word/train/wandb/run-20250508_222510-recjwpp0/logs/debug-internal.log
2025-05-08 22:25:10,906 INFO    MainThread:40425 [wandb_init.py:init():616] calling init triggers
2025-05-08 22:25:10,906 INFO    MainThread:40425 [wandb_init.py:init():623] wandb.init called with sweep_config: {}
config: {}
2025-05-08 22:25:10,906 INFO    MainThread:40425 [wandb_init.py:init():666] starting backend
2025-05-08 22:25:10,906 INFO    MainThread:40425 [wandb_init.py:init():670] setting up manager
2025-05-08 22:25:10,909 INFO    MainThread:40425 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-08 22:25:10,924 INFO    MainThread:40425 [wandb_init.py:init():678] backend started and connected
2025-05-08 22:25:10,929 INFO    MainThread:40425 [wandb_init.py:init():773] updated telemetry
2025-05-08 22:25:10,953 INFO    MainThread:40425 [wandb_init.py:init():806] communicating run to backend with 90.0 second timeout
2025-05-08 22:26:40,976 ERROR   MainThread:40425 [wandb_init.py:init():832] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2025-05-08 22:26:40,976 ERROR   MainThread:40425 [wandb_init.py:init():1251] error in wandb.init()
Traceback (most recent call last):
  File "/public/home/xiangyuduan/anaconda3/envs/rstar/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1241, in init
    return wi.init()
  File "/public/home/xiangyuduan/anaconda3/envs/rstar/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 838, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2025-05-08 22:26:41,005 WARNING MsgRouterThr:40425 [router.py:message_loop():77] message_loop has been closed
